// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManager.Models;

#nullable disable

namespace PropertyManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318231135_InitialMidtermMaster")]
    partial class InitialMidtermMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyManager.Models.Invoices", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExported")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("RentScheduleScheduleID")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("RentScheduleScheduleID");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            InvoiceDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsExported = false,
                            ProjectID = 1,
                            TotalAmount = 2850.00m
                        },
                        new
                        {
                            InvoiceID = 2,
                            InvoiceDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsExported = true,
                            ScheduleID = 2,
                            TotalAmount = 1200.00m
                        },
                        new
                        {
                            InvoiceID = 3,
                            InvoiceDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsExported = false,
                            ProjectID = 2,
                            TotalAmount = 180.00m
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.MaintenanceProjects", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("AssignedVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("PropertyID");

                    b.ToTable("MaintenanceProjects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            AssignedVendor = "RoofMaster LLC",
                            BidAmount = 2850.00m,
                            ProjectTitle = "Fix leaking roof",
                            PropertyID = 1,
                            Status = 1
                        },
                        new
                        {
                            ProjectID = 2,
                            AssignedVendor = "CoolAir Services",
                            BidAmount = 180.00m,
                            ProjectTitle = "HVAC Inspection",
                            PropertyID = 2,
                            Status = 4
                        },
                        new
                        {
                            ProjectID = 3,
                            AssignedVendor = "PlumbQuick",
                            BidAmount = 320.00m,
                            ProjectTitle = "Kitchen Faucet Repair",
                            PropertyID = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyID");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyID = 1,
                            Address = "1420 Lincoln Ave, Newburgh, IN",
                            MonthlyRent = 1200.00m,
                            PropertyName = "Maple Grove",
                            UnitNum = "101"
                        },
                        new
                        {
                            PropertyID = 2,
                            Address = "200 State St, Newburgh, IN",
                            MonthlyRent = 1500.00m,
                            PropertyName = "Riverview",
                            UnitNum = "A2"
                        },
                        new
                        {
                            PropertyID = 3,
                            Address = "55 Highland Rd, Evansville, IN",
                            MonthlyRent = 950.00m,
                            PropertyName = "Hidden Creek",
                            UnitNum = "10"
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.RentPayment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentScheduleScheduleID")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("RentScheduleScheduleID");

                    b.ToTable("RentPayments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            AmountPaid = 1200.00m,
                            PaymentDate = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "ACH",
                            ScheduleID = 2,
                            TransactionReference = "TXN778899"
                        },
                        new
                        {
                            PaymentID = 2,
                            AmountPaid = 500.00m,
                            PaymentDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            ScheduleID = 3,
                            TransactionReference = "TXN112233"
                        },
                        new
                        {
                            PaymentID = 3,
                            AmountPaid = 100.00m,
                            PaymentDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ScheduleID = 2,
                            TransactionReference = "CASH-001"
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.RentSchedules", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<decimal>("BaseRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LateFeeOccured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("TenantID");

                    b.ToTable("RentSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            BaseRent = 1200.00m,
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LateFeeOccured = 0.00m,
                            ReminderCount = 0,
                            Status = 0,
                            TenantID = 1
                        },
                        new
                        {
                            ScheduleID = 2,
                            BaseRent = 1200.00m,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LateFeeOccured = 0.00m,
                            ReminderCount = 0,
                            Status = 1,
                            TenantID = 2
                        },
                        new
                        {
                            ScheduleID = 3,
                            BaseRent = 1500.00m,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LateFeeOccured = 50.00m,
                            ReminderCount = 0,
                            Status = 2,
                            TenantID = 3
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.HasKey("TenantID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantID = 1,
                            Email = "archie@usi.edu",
                            FirstName = "Archie",
                            LastName = "Bald",
                            PhoneNum = "812-555-0101",
                            PropertyID = 1
                        },
                        new
                        {
                            TenantID = 2,
                            Email = "sarah.j@gmail.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            PhoneNum = "812-555-0142",
                            PropertyID = 1
                        },
                        new
                        {
                            TenantID = 3,
                            Email = "mike.r@yahoo.com",
                            FirstName = "Michael",
                            LastName = "Rodriguez",
                            PhoneNum = "812-555-0789",
                            PropertyID = 2
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.WorkLogs", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClockOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GPSLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialsUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("ProofPhotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.HasIndex("ProjectID");

                    b.ToTable("WorkLogs");

                    b.HasData(
                        new
                        {
                            LogID = 1,
                            ClockInTime = new DateTime(2026, 3, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2026, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GPSLocation = "37.94, -87.40",
                            MaterialsUsed = "Shingles, Tar",
                            ProjectID = 1,
                            ProofPhotoURL = "",
                            VendorSignature = "Signed-Digitally-01"
                        },
                        new
                        {
                            LogID = 2,
                            ClockInTime = new DateTime(2026, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2026, 3, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            GPSLocation = "37.94, -87.41",
                            MaterialsUsed = "Air Filter",
                            ProjectID = 2,
                            ProofPhotoURL = "",
                            VendorSignature = "Signed-Digitally-02"
                        },
                        new
                        {
                            LogID = 3,
                            ClockInTime = new DateTime(2026, 3, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2026, 3, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            GPSLocation = "37.94, -87.40",
                            MaterialsUsed = "New Faucet, Teflon Tape",
                            ProjectID = 3,
                            ProofPhotoURL = "",
                            VendorSignature = "Signed-Digitally-03"
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.Invoices", b =>
                {
                    b.HasOne("PropertyManager.Models.MaintenanceProjects", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.HasOne("PropertyManager.Models.RentSchedules", "RentSchedule")
                        .WithMany()
                        .HasForeignKey("RentScheduleScheduleID");

                    b.Navigation("Project");

                    b.Navigation("RentSchedule");
                });

            modelBuilder.Entity("PropertyManager.Models.MaintenanceProjects", b =>
                {
                    b.HasOne("PropertyManager.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManager.Models.RentPayment", b =>
                {
                    b.HasOne("PropertyManager.Models.RentSchedules", "RentSchedule")
                        .WithMany()
                        .HasForeignKey("RentScheduleScheduleID");

                    b.Navigation("RentSchedule");
                });

            modelBuilder.Entity("PropertyManager.Models.RentSchedules", b =>
                {
                    b.HasOne("PropertyManager.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyManager.Models.Tenant", b =>
                {
                    b.HasOne("PropertyManager.Models.Property", "Property")
                        .WithMany("Tenants")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManager.Models.WorkLogs", b =>
                {
                    b.HasOne("PropertyManager.Models.MaintenanceProjects", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PropertyManager.Models.Property", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
